# This workflow will build Cerberus and perform Mutation Analysis

name: Mutation Analysis 99%

on:
  push:
    branches: [ main, proceeding, betterment ]
  pull_request:
    branches: [ main, proceeding, betterment ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Mutation Analysis
        run: ./gradlew pitest
